name: guardian_view
description: "Guardian view app ,alerts of weapon detection."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.4
  dartz: ^0.10.1
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  provider: ^6.1.1
  device_preview: ^1.1.0
  connectivity_plus: ^5.0.2
  logger: ^2.0.2+1
  uuid: ^4.2.2
  iconly: ^1.0.1
  flutter_screenutil: ^5.9.0
  rxdart: ^0.27.7
  firebase_storage: ^11.5.6
  swipe_to: ^1.0.5
  file_picker: ^6.1.1
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.5
  mocktail: ^1.0.2

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/vectors/
    - assets/lottie_jsons/
    - assets/images/


fonts:
  - family: Beautiful-people-font
    fonts:
      - asset: assets/fonts/beautiful-people-font/BeautifulPeoplePersonalUse-dE0g.ttf
  - family: Agbalumo
    fonts:
      - asset: assets/fonts/Agbalumo/Agbalumo-Regular.ttf
  - family: Bite-chocolate-font
    fonts:
      - asset: assets/fonts/bite-chocolate-font/BiteChocolate-2RGl.ttf
  - family: Snowburst_One
    fonts:
      - asset: assets/fonts/Snowburst_One/SnowburstOne-Regular.ttf
