// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSnGgWK37DAxRXJA-hDgTdCIYJmbGtKW0',
    appId: '1:667461757610:web:ef9eaf5fa737be6b3abed3',
    messagingSenderId: '667461757610',
    projectId: 'guardianmock',
    authDomain: 'guardianmock.firebaseapp.com',
    storageBucket: 'guardianmock.appspot.com',
    measurementId: 'G-QX3CS1907E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClzOaDFggch6dk4qhejDsoAx5XY7noeAI',
    appId: '1:667461757610:android:552639deaed2bd823abed3',
    messagingSenderId: '667461757610',
    projectId: 'guardianmock',
    storageBucket: 'guardianmock.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmL1gV7gsLc8TjGGPWXWXYUgfdgvCqlWE',
    appId: '1:667461757610:ios:7583e9370a9586a93abed3',
    messagingSenderId: '667461757610',
    projectId: 'guardianmock',
    storageBucket: 'guardianmock.appspot.com',
    iosBundleId: 'com.example.guardianView',
  );
}
