// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlABSj3dOPYSrkczSEO0MdW4LPPVzHsZI',
    appId: '1:800381544768:web:ed5998b50c4f6123e772a5',
    messagingSenderId: '800381544768',
    projectId: 'guradianview',
    authDomain: 'guradianview.firebaseapp.com',
    storageBucket: 'guradianview.appspot.com',
    measurementId: 'G-V9BVCF3ME2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKp0r3Ky-4Dytrxa1RmeTxkXSEtxbfJDI',
    appId: '1:800381544768:android:951a7161e6c83aaee772a5',
    messagingSenderId: '800381544768',
    projectId: 'guradianview',
    storageBucket: 'guradianview.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJQLVVHuy-RiyJR353XDS6beHj2IXJGb4',
    appId: '1:800381544768:ios:6602c2e1081b7086e772a5',
    messagingSenderId: '800381544768',
    projectId: 'guradianview',
    storageBucket: 'guradianview.appspot.com',
    iosBundleId: 'com.example.guardianView',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJQLVVHuy-RiyJR353XDS6beHj2IXJGb4',
    appId: '1:800381544768:ios:4f3a5cdc56dfefcae772a5',
    messagingSenderId: '800381544768',
    projectId: 'guradianview',
    storageBucket: 'guradianview.appspot.com',
    iosBundleId: 'com.example.guardianView.RunnerTests',
  );
}
